### ISSUE TITLE
type 'String' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by zyllus17** [bizz84/coronavirus_rest_api_flutter_course#2]
I completed the entire course and it went well but in the second last video, it has been throwing this error. I don't understand where I am making the mistake.

Error :

![Error](https://user-images.githubusercontent.com/50977126/98124640-74b9c400-1ed9-11eb-8b53-1e84776a84e7.png)

And when I check where the error is on #1 , it shows the error on 

```final value = sharedPreferences.getInt(endpointValueKey(endpoint));```

![image](https://user-images.githubusercontent.com/50977126/98125049-f3aefc80-1ed9-11eb-94b3-f43f71fb100c.png)

I copied your entire code when I couldn't solve it yet the error doesn't go away.

**Comment by bizz84** [comment]
@zyllus17 You may have written it once as a `String` by mistake, and now it fails every time when you try to read it from shared preferences.
Delete/uninstall the app, then try again.

**Comment by zyllus17** [comment]
> @zyllus17 You may have written it once as a `String` by mistake, and now it fails every time when you try to read it from shared preferences.
> Delete/uninstall the app, then try again.

Tried it and it actually worked. Thank you!
